### ISSUE TITLE
Fixnum is deprecated in Ruby 2.4

### ISSUE THREAD

**Issue by david-gregory-inmar** [florianpilz/micro-optparse#12]
~/.rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/micro-optparse-1.2.0/lib/micro-optparse/parser.rb:49: warning: constant ::Fixnum is deprecated

**Comment by florianpilz** [comment]
Finally fixed and also pushed a new version (1.2.1) to Rubygems with the fix.
